-- 1. Profiles Table (Extends auth.users)
create table if not exists profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  name text,
  store_name text,
  avatar_url text,
  phone text,
  location text,
  bio text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Favorites Table
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  product_id bigint references products(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, product_id)
);

-- 3. Chat Rooms (Conversations)
create table if not exists chat_rooms (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id),
  buyer_id uuid references auth.users(id),
  seller_id uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(product_id, buyer_id, seller_id)
);

-- 4. Messages
create table if not exists messages (
  id bigint generated by default as identity primary key,
  room_id bigint references chat_rooms(id) on delete cascade not null,
  sender_id uuid references auth.users(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Notifications
create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  type text not null, -- 'price', 'message', 'system', 'alert'
  title text not null,
  message text not null,
  link text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Security)
alter table profiles enable row level security;
alter table favorites enable row level security;
alter table chat_rooms enable row level security;
alter table messages enable row level security;
alter table notifications enable row level security;

-- Profiles: Public read, Self update
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Favorites: Self read/write
create policy "Users can view own favorites" on favorites for select using (auth.uid() = user_id);
create policy "Users can insert own favorites" on favorites for insert with check (auth.uid() = user_id);
create policy "Users can delete own favorites" on favorites for delete using (auth.uid() = user_id);

-- Chat: Participants read/write
create policy "Users can view own chats" on chat_rooms for select using (auth.uid() = buyer_id or auth.uid() = seller_id);
create policy "Users can create chats" on chat_rooms for insert with check (auth.uid() = buyer_id);

create policy "Users can view messages in their rooms" on messages for select using (
  exists (select 1 from chat_rooms where id = messages.room_id and (buyer_id = auth.uid() or seller_id = auth.uid()))
);
create policy "Users can send messages in their rooms" on messages for insert with check (
  exists (select 1 from chat_rooms where id = room_id and (buyer_id = auth.uid() or seller_id = auth.uid()))
);

-- Notifications: Self read
create policy "Users can view own notifications" on notifications for select using (auth.uid() = user_id);
