-- Habilitar a extensão UUID (geralmente já vem habilitada, mas bom garantir)
create extension if not exists "uuid-ossp";

-- 1. Tabela de Categorias
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inserir categorias padrão
insert into categories (name, icon) values
  ('Imóveis', 'home'),
  ('Autos', 'car'),
  ('Autopeças', 'wrench'),
  ('Celulares e Telefonia', 'smartphone'),
  ('Casa e Decoração', 'sofa'),
  ('Esportes e Fitness', 'bike'),
  ('Serviços', 'briefcase')
on conflict do nothing;

-- 2. Tabela de Produtos
create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  category_id bigint references categories(id),
  image text, -- URL da imagem principal
  images text[], -- Array de URLs de imagens
  location text default 'Brasil',
  seller_name text,
  seller_avatar text,
  user_id uuid references auth.users(id), -- Link opcional com usuário logado
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Configurar Policies de Segurança (RLS)
alter table products enable row level security;
alter table categories enable row level security;

-- Remover policies antigas para evitar erro de duplicidade
drop policy if exists "Public read products" on products;
drop policy if exists "Leitura pública de produtos" on products;
drop policy if exists "Public read categories" on categories;
drop policy if exists "Anon insert products" on products;

-- Recriar policies
create policy "Public read products" on products for select using (true);
create policy "Public read categories" on categories for select using (true);
create policy "Anon insert products" on products for insert with check (true);
